language: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
      - ppa:graphics-drivers/ppa
    packages: 
      - nvidia-cuda-toolkit-8.0

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
