language: cpp
dist: xenial
compiler:
  - gcc
os:
  - linux
env: 
#  - CUDA=8.0
  - CXX=g++-8

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
#      - sourceline: 'ppa:graphics-drivers/ppa'
    packages: 
      - g++-8
      - libgoogle-glog-dev
      - libgtest-dev
      - libopencv-dev
      - libboost-all-dev
      - libavcodec-dev
      - libavformat-dev
      - nvidia-cuda-toolkit

script:
#  - source .travis/install-cuda-trusty.sh
#  - export CXX=g++-7
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
