language: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:graphics-drivers/ppa'
    packages: 
      - nvidia-cuda-toolkit

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
