language: cpp
dist: xenial
compiler:
  - gcc
os:
  - linux
env: 
#  - CUDA=8.0
#   - COMPILER=g++-8
#   - CXX=g++-8
  - CC_COMPILER=gcc-8
  - CXX_COMPILER=g++-8

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
 #     - sourceline: 'ppa:mhier/libboost-latest'
#      - sourceline: 'ppa:graphics-drivers/ppa'
    packages: 
      - g++-8
      - libgoogle-glog-dev
      - libgtest-dev
      - libopencv-dev
      - libavcodec-dev
      - libavformat-dev
      - nvidia-cuda-toolkit
#      - libboost1.67-all-dev
      #- libboost-python-dev
      - apt-file

before_install:
    - export CXX=g++-8
    - export  CC=gcc-8

install:
  - |
        export BOOST_VERSION=1.65.1
        export BOOST_URL=https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
        mkdir -p boost${BOOST_VERSION}
        travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost${BOOST_VERSION}
        pushd boost${BOOST_VERSION}
        ./bootstrap.sh --with-libraries=python,filesystem,system
        ./b2 -j4 -d0 install
        popd

script:
#  - source .travis/install-cuda-trusty.sh
#  - export CXX=g++-8
#  - locate relative_difference.hpp
  #- ls /usr/include/boost/math/special_functions
  - apt search libboost-pyth
  - ls /usr/include/boost/math
  - locate type.hpp
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
