language: cpp
dist: xenial
compiler:
  - gcc
os:
  - linux
env: 
  - CUDA=8.0
   
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:graphics-drivers/ppa'
    packages: 
      - g++-8
      - libgoogle-glog-dev
      - nvidia-cuda-toolkit
      - libopencv-dev

script:
#  - source .travis/install-cuda-trusty.sh
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
