language: cpp
services:
  - docker
dist: xenial

install:
  - docker pull lightdb:environment
  - docker build -t lightdb:core -f docker/Dockerfile.lightdb .

script:
  - docker run lightdb:core ./script/test

after_success:
  - docker build -t travis-docker-prod -f Dockerfile.prod .
  - ./script/upload-to-docker-hub
#- notify on Slack \o/

#  - mkdir -p build
#  - cd build
#  - cmake .. $CMAKE_OPTIONS
#  - make
#  - make test
#  - ctest
