language: cpp
dist: xenial
compiler:
  - gcc
os:
  - linux
env: 
#  - CUDA=8.0
#   - COMPILER=g++-8
#   - CXX=g++-8

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:mhier/libboost-latest'
#      - sourceline: 'ppa:graphics-drivers/ppa'
    packages: 
      - g++-8
      - libgoogle-glog-dev
      - libgtest-dev
      - libopencv-dev
      - libavcodec-dev
      - libavformat-dev
      - nvidia-cuda-toolkit
      - libboost1.67

before_install:
    - export CXX=g++-8
    - export  CC=gcc-8

script:
#  - source .travis/install-cuda-trusty.sh
#  - export CXX=g++-8
#  - locate relative_difference.hpp
  #- ls /usr/include/boost/math/special_functions
  - locate boost
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
