language: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux

addons:
  apt:
    packages: 
      - nvidia-cuda-toolkit

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - ctest
